---
- hosts: webservers
  become: yes
  vars: 
    var1: Niru
    var2: San
  tasks: 
   - name: display playbook vars vrr1
     debug: 
      msg: "{{vrr2}}"
   - name: diplay group vars
     debug: 
      msg: "{{mycompname}}"