---
- hosts: webservers
  become: yes
  vars: 
    var1: Niru
    var2: San
  tasks: 
   - name: display playbook vars vrr1
     debug: 
      msg: "{{var1}}"
   - name: display group vars
     debug: 
      msg: "{{mycompname}}"