---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on ubuntu
    apt: 
     name: apache2
     state: present

  - name: want to start webserver on ubuntu
    service: 
      name: apache2
      state: present
