--- 
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on redhat
    yum: 
      name: httpd
      state: present
    notify: restarthttpd

  - name: copy index file into all nodes
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: restarthttpd

  
  handlers: 
   - name: restarthttpd 
     service: 
      name: httpd
      state: restarted
  
